/*!
* PerForms Framework v0.8.0
* https://github.com/tagcosta/PerForms
*
* Copyright 2010, Tiago Costa
* Licensed under the GPL Version 2 license.
* http://www.gnu.org/licenses/gpl-2.0.html
* 
* The following projects made PerForms possible:
* jQuery: http://jquery.com/
* jQueryUI: http://jqueryui.com/
* jQuery blockUI: http://malsup.com/jquery/block/
* jqGrid: http://www.trirand.com/blog/
* jQuery tmpl: https://github.com/jquery/jquery-tmpl
* JSON: http://www.json.org/js.html
* Valums AJAX Upload: http://valums.com/ajax-upload/
* jQuery UI Multiselect: http://quasipartikel.at/multiselect_next/
* NewtonSoftJSON: http://james.newtonking.com/pages/json-net.aspx
* NPOI: http://npoi.codeplex.com/
* NHibernate: http://nhforge.org/
*/
function performs_AJAX(f){this.WebServiceURL="PerForms/PerFormsWS.asmx";this.MethodName=f;this.Args=[];this.add=function(h,a){this.Args[this.Args.length]=new performs_KeyValue(h,JSON.stringify(a))};this.addKeyValues=function(h){var a=[],b=[],e;for(e=0;e<h.length;e+=1){a[a.length]=h[e].Key;b[b.length]=h[e].Value}this.add("keys",a);this.add("values",b)};this.request=function(h){var a,b;a="{";for(b=0;b<this.Args.length;b+=1){a+=this.Args[b].Key+":"+this.Args[b].Value;if(b<this.Args.length-1)a+=","}a+=
"}";try{$.ajax({type:"POST",url:this.WebServiceURL+"/"+this.MethodName,data:a,contentType:"application/json; charset=utf-8",dataType:"json",success:function(d){d.d===undefined?h(d):h(d.d)},error:function(d){d.responseText!=null?performs_showMessageDialog("ERROR",performs_Translate("[ERROR]"),"",d.responseText):performs_showMessageDialog("ERROR",performs_Translate("[ERROR]"),"",d.get_responseText)}})}catch(e){performs_showMessageDialog("ERROR",performs_Translate("[ERROR]"),"",e)}}}
function performs_blockUI(f,h){$.blockUI({theme:true,title:f,message:h})}function performs_unblockUI(){$.unblockUI()}function performs_block(f,h,a){$(f).block({theme:true,title:h,message:a})}function performs_unblock(f){$(f).unblock()}var performs_KeyValue=function(f,h){this.Key=f;this.Value=h};function performs_SplitTokenString(f){var h=f.split("");if(h[0]!="["||h[h.length-1]!="]")return[f];f=f.split("][");return f.length>1?$.map(f,function(a,b){return b==0?a+"]":a.slice(0,a.length-1)}):f}
function performs_showMessageDialog(f,h,a,b){performs_showMessageDialog(f,h,a,b,null)}
function performs_showMessageDialog(f,h,a,b,e){if(h!=null&&h!="")h=performs_Translate(h);if(a!=null&&a!="")a=performs_Translate(a);if(b!=null&&b!="")b=performs_Translate(b);var d="ui-state-highlight";if(f=="ERROR"||f=="0")d="ui-state-error";f="";f+="<div class='ui-widget ui-helper-hidden'>";f+="   <div class='"+d+" ui-corner-all' style='padding: 0 .7em;'>";f+="       <p>";f+="           <span class='ui-icon ui-icon-alert' style='float: left; margin-right: .3em;'></span>";f+=a!=null&&a!=""?"       <span class='message'><strong>"+
a+": </strong>"+b+"</span>":"       <span class='message'>"+b+"</span>";f+="       </p>";f+="   </div>";f+="</div>";$(f).dialog({modal:true,title:h,draggable:false,resizable:false,buttons:{Ok:function(){$(this).dialog("close")}},close:function(){e!=null&&e()}})}
var performs_Validation=function(f,h){this.RegEx=f;this.Message=h;this.isValid=function(a){return a==""||RegExp(this.RegEx).test(a)}},performs_GetAJAXActions=function(f,h,a){if(f.validateGroup(a)){a=f.getGroupKeyValues(a);var b=new performs_AJAX("GetAJAXActions");b.addKeyValues(a);b.add("actionKey",h);performs_block("#"+f.FormKey,performs_Translate("[INFO]"),performs_Translate("[PleaseWait]"));b.request(function(e){performs_unblock("#"+f.FormKey);$(e.Actions).each(function(d,c){switch(c.AJAXActionType){case 0:performs_showMessageDialog(c.MessageType,
c.MessageTitle,c.MessageSubtitle,c.MessageContent);break;case 1:if(f.NextForm!=null){f.NextForm.FormKey!=f.FormKey&&f.NextForm.remove();f.NextForm=null}var g=$("#"+f.FormKey).parent();g.append(c.Form);g=g.find("div.performs-form-div:last").data("Perform");if(g!=null){f.NextForm=g;g.PreviousForm=f}switch(c.PreviousFormActionType){case 1:$("#"+f.FormKey).data("Perform").hideFooter();break;case 2:$("#"+f.FormKey).hide();break;case 3:$("#"+f.FormKey).remove();if(g!=null)g.PreviousForm=null}break;case 2:g=
f.getFieldByKey(c.FieldKey);g.updateItems(c.KeyValues);break;case 3:window.location=e.RedirectToURL;break;case 4:g=f.getFieldByKey(c.FieldKey);g.setValues(c.Values)}})})}},performs_Form=function(f,h){this.FormKey=f;this.Header=h.header||"";this.Footer=h.footer||"";this.MinWidth=h.minWidth||"100%";this.LabelWidth=h.labelWidth||"0";this.Fields=[];this.FormReady="";this.Groups=[];this.Groups[0]=new performs_KeyValue("ALL",[]);this.TabAreas=[];this.tabCounter=0;this.PreviousForm=this.NextForm=null;this.onFormReady=
function(){(new Function("form",this.FormReady))(this);$("#performs-form-"+this.FormKey+" div.performs-tabarea-div").tabs();$("#performs-form-"+this.FormKey+" input:visible:first").focus()};this.removeMergeWithNextOnLastField=function(){this.Fields[this.Fields.length-1].MergeWithNext=false};this.removeInvalidTabAreasAndTabs=function(){for(var a=0;a<this.TabAreas.length;a++)if(this.TabAreas[a].open){this.TabAreas.splice(a,1);a--}else{for(var b=0;b<this.TabAreas[a].tabs.length;b++)if(this.TabAreas[a].tabs[b].open||
this.TabAreas[a].tabs[b].startIndex>this.TabAreas[a].tabs[b].endIndex){this.TabAreas[a].tabs.splice(b,1);b--}if(this.TabAreas[a].tabs.length==0){this.TabAreas.splice(a,1);a--}}};this.calcMerges=function(){var a=false;$(this.Fields).each(function(b,e){if(e.MergeWithNext){if(a)e.ContinueMerge=true;else e.BeginMerge=true;a=true}else{if(a)e.EndMerge=true;else e.NoMerge=true;a=false}})};this.calcTabAreasAndTabs=function(){var a=this;$(this.TabAreas).each(function(b,e){a.Fields[e.startIndex].BeginTabAreas[a.Fields[e.startIndex].BeginTabAreas.length]=
e;a.Fields[e.endIndex].EndTabAreas[a.Fields[e.endIndex].EndTabAreas.length]=e;$(e.tabs).each(function(d,c){a.Fields[c.startIndex].BeginTabs[a.Fields[c.startIndex].BeginTabs.length]=c;a.Fields[c.endIndex].EndTabs[a.Fields[c.endIndex].EndTabs.length]=c})})};this.renderForm=function(){var a=this;this.removeMergeWithNextOnLastField();this.removeInvalidTabAreasAndTabs();this.calcMerges();this.calcTabAreasAndTabs();var b="";b+="<table cellspacing='0' id='performs-form-"+this.FormKey+"' class='ui-widget performs-form' width='"+
this.MinWidth+"'>";if(this.Header.length>0)b+=this.renderHeader();b+="<tr class='ui-widget-content'><td class='performs-form-content'><table cellspacing='0' width='100%'>";$(this.Fields).each(function(e,d){d.LabelWidth=a.LabelWidth;if(d.BeginTabs.length>d.BeginTabAreas.length)b+="<div id='"+a.FormKey+"-tab-"+d.BeginTabs[0].number+"'><table cellspacing='0'>";d.BeginTabAreas.length>0&&$(d.BeginTabAreas).each(function(g,i){b+="<tr><td colspan='2'><div class='performs-tabarea-div'><ul>";$(i.tabs).each(function(j,
k){b+="<li><a href='#"+a.FormKey+"-tab-"+k.number+"'>"+k.label+"</a></li>"});b+="</ul><div id='"+a.FormKey+"-tab-"+i.tabs[0].number+"'><table cellspacing='0'>"});if(d.BeginMerge){var c=$("<div />");$("#performs_template_label").tmpl(d).appendTo(c);b+="<tr>"+c.html();d.FieldLabel="";d.LabelWidth="0";b+="<td><table cellspacing='0' cellpadding='0'><tr><td><table cellspacing='0' cellpadding='0'>"+d.renderField()+"</table></td>"}if(d.ContinueMerge){d.LabelWidth="0";b+="<td><table cellspacing='0' cellpadding='0'>"+
d.renderField()+"</table></td>"}if(d.EndMerge){d.LabelWidth="0";b+="<td><table cellspacing='0'>"+d.renderField()+"</table></td></tr></table></td></tr>"}if(d.NoMerge)b+=d.renderField();d.EndTabAreas.length>0&&$(d.EndTabAreas).each(function(){b+="</table></div></div></td></tr>"});if(d.EndTabs.length>d.EndTabAreas.length)b+="</table></div>"});b+="</table></td></tr>";if(this.Footer.length>0)b+=this.renderFooter();b+="</table>";return b};this.renderHeader=function(){return"<tr class='ui-widget-header'><td class='performs-form-header'>"+
this.Header+"</td></tr>"};this.renderFooter=function(){return"<tr class='ui-widget-header'><td class='performs-form-footer'>"+this.Footer+"</td></tr>"};this.hideFooter=function(){$("#"+this.FormKey+" td.performs-form-footer").parent().hide()};this.showFooter=function(){$("#"+this.FormKey+" td.performs-form-footer").parent().show()};this.getFieldByKey=function(a){var b=null;$(this.Fields).each(function(e,d){if(d.FieldKey==a)b=d});return b};this.getFieldsByGroup=function(a){var b=[],e=this;$(this.Groups).each(function(d,
c){c.Key==a&&$(c.Value).each(function(g,i){b[b.length]=e.getFieldByKey(i)})});return b};this.getGroupKeyValues=function(a){var b=[];a=this.getFieldsByGroup(a);$(a).each(function(e,d){if(d.FieldType!="FieldButton"&&(d.FieldType=="FieldLabel"||!d.Hidden)){var c=d.getValues();$(c).each(function(g,i){b[b.length]=new performs_KeyValue(d.FieldKey,i)})}});return b};this.addGroup=function(a,b){this.Groups[this.Groups.length]=new performs_KeyValue(a,b)};this.validateGroup=function(a){var b=true;a=this.getFieldsByGroup(a);
$(a).each(function(e,d){if(b)b=d.validate();else d.validate()});return b};this.remove=function(){$("#"+this.FormKey).remove()};this.addTabArea=function(){var a={};a.tabs=[];a.open=true;a.startIndex=this.Fields.length;this.TabAreas[this.TabAreas.length]=a;return this};this.endTabArea=function(){for(var a=this.TabAreas.length-1;a>=0;a--)if(this.TabAreas[a].open){this.TabAreas[a].open=false;this.TabAreas[a].endIndex=this.Fields.length-1;break}return this};this.addTab=function(a){for(var b=this.TabAreas.length-
1;b>=0;b--)if(this.TabAreas[b].open){var e={};e.label=a;e.open=true;e.startIndex=this.Fields.length;e.number=this.tabCounter++;this.TabAreas[b].tabs[this.TabAreas[b].tabs.length]=e;break}return this};this.endTab=function(){for(var a=false,b=this.TabAreas.length-1;b>=0;b--){if(this.TabAreas[b].open)for(var e=this.TabAreas[b].tabs.length-1;e>=0;e--)if(this.TabAreas[b].tabs[e].open){this.TabAreas[b].tabs[e].open=false;this.TabAreas[b].tabs[e].endIndex=this.Fields.length-1;a=true;break}if(a)break}return this};
this.addFieldText=function(a,b,e){b=new performs_FieldText(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);return b};this.addFieldTextArea=function(a,b,e){b=new performs_FieldTextArea(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);return b};this.addFieldRadios=function(a,b,
e,d){b=new performs_FieldRadios(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyRadios();";return b};this.addFieldCheckBoxes=function(a,b,e,d){b=new performs_FieldCheckBoxes(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);
this.FormReady+="form.getFieldByKey('"+a+"').applyCheckBoxes();";return b};this.addFieldComboBox=function(a,b,e,d){b=new performs_FieldComboBox(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyComboBox();";return b};this.addFieldButton=function(a,b,e,d){b=new performs_FieldButton(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);
this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyButton();";return b};this.addFieldMultiSelectBox=function(a,b,e,d){b=new performs_FieldMultiSelectBox(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyMultiSelectBox();";return b};
this.addFieldGridView=function(a,b,e,d,c,g,i,j,k){b=new performs_FieldGridView(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d,c,g,i,j,k);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyGridView();";return b};this.addFieldLabel=function(a,b,e){b=new performs_FieldLabel(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=
a;this.addGroup(a,[a]);return b};this.addFieldDate=function(a,b,e){b=new performs_FieldDate(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyDatePicker();";return b};this.addFieldUpload=function(a,b,e,d){b=new performs_FieldUpload(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=
a;this.addGroup(a,[a]);this.FormReady+="form.getFieldByKey('"+a+"').applyUpload();";return b};this.addFieldFree=function(a,b,e,d,c,g){b=new performs_FieldFree(this,"performs-form-"+this.FormKey+"-field-"+a,a,b,e,d,c,g);this.Fields[this.Fields.length]=b;this.Groups[0].Value[this.Groups[0].Value.length]=a;this.addGroup(a,[a]);return b}},performs_Field=function(){this.base=function(f,h,a,b,e,d,c,g){this.Form=f;this.FieldID=h;this.FieldKey=a;this.FieldLabel=b;this.FieldType=e;this.FieldClass=d;this.FieldTemplate=
c;this.Validations=[];this.Hidden=this.EagerValidation=false;this.Required=g==null||g.required==null?false:g.required;this.MergeWithNext=g==null||g.mergeWithNext==null?false:g.mergeWithNext;this.NoMerge=this.ContinueMerge=this.EndMerge=this.BeginMerge=false;this.BeginTabAreas=[];this.EndTabAreas=[];this.BeginTabs=[];this.EndTabs=[]};this.hide=function(){$("#"+this.FieldID).hide();this.Hidden=true};this.show=function(){$("#"+this.FieldID).show();this.Hidden=false};this.addValidation=function(f,h){this.Validations[this.Validations.length]=
new performs_Validation(f,h)};this.validate=this.base_validate=function(f){var h=[];if($("#"+this.FieldID).is(":visible")){$(this.Validations).each(function(a,b){$(f).each(function(e,d){if(!b.isValid(d))h[h.length]=b.Message})});if(this.Required&&f.length==1&&(f[0]==null||f[0]==""))h[h.length]=performs_Translate("[RequiredField]")}return h};this.clearErrorMessages=function(){$("#"+this.FieldID+" .performs-field-message").html("");$("#"+this.FieldID+" .performs-field-content").removeClass("ui-state-error")};
this.showErrorMessages=function(f){this.clearErrorMessages();var h=this;$(f).each(function(a,b){var e=$("#"+h.FieldID+" .performs-field-message");e.html(e.html()+"<div><span class='ui-icon ui-icon-alert' style='float: left;'></span><span>"+b+"</span></div>");a!=$(f).length-1&&e.html(e.html()+"<br />");$("#"+h.FieldID+" .performs-field-content").addClass("ui-state-error")})}},performs_FieldText=function(f,h,a,b,e){this.base(f,h,a,b,"FieldText","performs-field-fieldtext","performs_fieldtemplate_text",
e);this.validate=function(){if(!this.EagerValidation){this.EagerValidation=true;var d=this;$("#"+this.FieldID+" input:text").bind("keyup",function(){d.validate()})}var c=this.base_validate(this.getValues());this.showErrorMessages(c);return c.length==0};this.getValues=function(){return[$("#"+this.FieldID+" input:text")[0].value]};this.setValues=function(d){$("#"+this.FieldID+" input:text")[0].value=d[0]};this.renderField=function(){var d=this;$("#"+this.FieldID+" input:text").live("hover",function(){$(this).toggleClass("ui-state-hover")}).live("focus",
function(){$(this).addClass("ui-state-focus")}).live("blur",function(){$(this).removeClass("ui-state-focus");d.validate()});var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()}};performs_FieldText.prototype=new performs_Field;
var performs_FieldTextArea=function(f,h,a,b,e){this.base(f,h,a,b,"FieldTextArea","performs-field-fieldtextarea","performs_fieldtemplate_textarea",e);this.validate=function(){if(!this.EagerValidation){this.EagerValidation=true;var d=this;$("#"+this.FieldID+" textarea").bind("keyup",function(){d.validate()})}var c=this.base_validate(this.getValues());this.showErrorMessages(c);return c.length==0};this.getValues=function(){return[$("#"+this.FieldID+" textarea")[0].value]};this.setValues=function(d){$("#"+
this.FieldID+" textarea")[0].value=d[0]};this.renderField=function(){var d=this;$("#"+this.FieldID+" textarea").live("hover",function(){$(this).toggleClass("ui-state-hover")}).live("focus",function(){$(this).addClass("ui-state-focus")}).live("blur",function(){$(this).removeClass("ui-state-focus");d.validate()});var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()}};performs_FieldTextArea.prototype=new performs_Field;
var performs_FieldRadios=function(f,h,a,b,e,d){this.base(f,h,a,b,"FieldRadios","performs-field performs-field-fieldradios","performs_fieldtemplate_radios",d);this.KeyValues=e;this.validate=function(){var c=this.base_validate(this.getValues());this.showErrorMessages(c);return c.length==0};this.getValues=function(){var c=$("#"+this.FieldID+" input:radio:checked")[0];if(c!=null)return[c.value];return[""]};this.setValues=function(c){var g=$("#"+this.FieldID+" input:radio");$(g).each(function(i,j){j.checked=
false;$(j).change().button("option","icons",{primary:"ui-icon-radio-on",secondary:null});if(j.value==c[0]){j.checked=true;$(j).change().button("option","icons",{primary:"ui-icon-check",secondary:null})}})};this.renderField=function(){$("#"+this.FieldID+" input:radio").live("focus",function(){$(this).next("label").addClass("ui-state-focus")}).live("blur",function(){$(this).next("label").removeClass("ui-state-focus")}).live("click",function(){$(this).parents(".performs-field-fieldradios:first input:radio[name = '"+
$(this)[0].name+"']").button("option","icons",{primary:"ui-icon-radio-on",secondary:null});$(this).button("option","icons",{primary:"ui-icon-check",secondary:null})});var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()};this.applyRadios=function(){$("#"+this.FieldID+" input:radio").button({icons:{primary:"ui-icon-radio-on",secondary:null}})};this.addConditionalVisibility=function(c,g){var i=this;$("#"+this.FieldID+" input:radio").click(function(){var j=false,k=i.getValues(),
l=i.Form.getFieldsByGroup(g);$(k).each(function(m,n){$(c).each(function(o,p){if(n==p)j=true})});j?$(l).each(function(m,n){n.show()}):$(l).each(function(m,n){n.hide()})})}};performs_FieldRadios.prototype=new performs_Field;
var performs_FieldCheckBoxes=function(f,h,a,b,e,d){this.base(f,h,a,b,"FieldCheckBoxes","performs-field-fieldcheckboxes","performs_fieldtemplate_checkboxes",d);this.KeyValues=e;this.validate=function(){if(!this.EagerValidation){this.EagerValidation=true;var c=this;$("#"+this.FieldID+" input:checkbox").bind("click",function(){c.validate()})}var g=this.base_validate(this.getValues());this.showErrorMessages(g);return g.length==0};this.getValues=function(){var c=$("#"+this.FieldID+" input:checkbox:checked");
if(c.length>0){var g=[];$(c).each(function(i,j){g[g.length]=j.value});return g}else return[""]};this.setValues=function(c){var g=$("#"+this.FieldID+" input:checkbox");$(g).each(function(i,j){j.checked=false;$(j).change().button("option","icons",{primary:"ui-icon-radio-on",secondary:null});$(c).each(function(k,l){if(j.value==l){j.checked=true;$(j).change().button("option","icons",{primary:"ui-icon-check",secondary:null})}})})};this.renderField=function(){var c=this;$("#"+this.FieldID+" input:checkbox").live("focus",
function(){$(this).next("label").addClass("ui-state-focus")}).live("blur",function(){$(this).next("label").removeClass("ui-state-focus")}).live("click",function(){$(this).is(":checked")?$(this).button("option","icons",{primary:"ui-icon-check",secondary:null}):$(this).button("option","icons",{primary:"ui-icon-radio-on",secondary:null});c.validate()});var g=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(g);return g.html()};this.applyCheckBoxes=function(){$("#"+this.FieldID+" input:checkbox").button({icons:{primary:"ui-icon-radio-on",
secondary:null}})}};performs_FieldCheckBoxes.prototype=new performs_Field;
var performs_FieldComboBox=function(f,h,a,b,e,d){this.base(f,h,a,b,"FieldComboBox","performs-field-fieldcombobox","performs_fieldtemplate_combobox",d);this.KeyValues=e;this.OnChange=function(){};this.validate=function(){var c=this.base_validate(this.getValues());this.showErrorMessages(c);return c.length==0};this.getValues=function(){var c=[""],g=$("#"+this.FieldID+" input:text")[0].value,i=$("#"+this.FieldID+" input:text").autocomplete("option","source");$(i).each(function(j,k){if(k.label.toLowerCase()==
g.toLowerCase())c=[k.id]});return c};this.setValues=function(c){var g=this,i=$("#"+this.FieldID+" input:text").autocomplete("option","source");$(i).each(function(j,k){k.id==c[0]&&$("#"+g.FieldID+" input:text:first").val(k.label)})};this.updateItems=function(c){var g=[];$(c).each(function(i,j){g[g.length]={id:j.Key,label:j.Value}});$("#"+this.FieldID+" input:text").autocomplete("option","source",g);$("#"+this.FieldID+" input:text").val("")};this.renderField=function(){$("#"+this.FieldID+" input:text").live("hover",
function(){$(this).toggleClass("ui-state-hover")}).live("focus",function(){$(this).addClass("ui-state-focus")}).live("blur",function(){$(this).removeClass("ui-state-focus")});var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()};this.applyComboBox=function(){var c=this,g=$("#"+this.FieldID+" input:text"),i=[];$(this.KeyValues).each(function(j,k){i[i.length]={id:k.Key,label:k.Value}});g.autocomplete({source:i,delay:0,minLength:0}).unbind("blur.autocomplete").blur(function(){var j=
this,k=false,l=$(this).autocomplete("option","source");$(l).each(function(m,n){if(n.label.toLowerCase()==j.value.toLowerCase())k=true});if(k){if($(this).prevAll("input:hidden")[0].value!=this.value){$(this).prevAll("input:hidden")[0].value=this.value;$(this).autocomplete("close");c.clearErrorMessages();c.OnChange()}}else this.value=""});$("<span style='position: absolute;' class='ui-state-default'><span style='margin-top: 5px; margin-left: 3px;' class='ui-icon ui-icon-triangle-1-s'></span></span>").insertAfter(g).width(25).height(g.height()+
10).hover(function(){$(this).toggleClass("ui-state-hover")}).click(function(){setTimeout(function(){g.focus();g.autocomplete("widget").is(":visible")?g.autocomplete("close"):g.autocomplete("search","");return false},100)});$("<input type='hidden' />").insertBefore(g)};this.addGetAJAXActions=function(c,g){var i=this;this.OnChange=function(){performs_GetAJAXActions(i.Form,c,g)}}};performs_FieldComboBox.prototype=new performs_Field;
var performs_FieldButton=function(f,h,a,b,e,d){this.base(f,h,a,e,"FieldButton","performs-field-fieldbutton","performs_fieldtemplate_button",d);this.ButtonLabel=b;this.validate=function(){return true};this.getValues=function(){return[""]};this.setValues=function(){};this.renderField=function(){var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()};this.applyButton=function(){$("#"+this.FieldID+" input:button").button()};this.addGetAJAXActions=function(c,g){var i=this;
$("#"+this.FieldID+" input:button").click(function(){performs_GetAJAXActions(i.Form,c,g)})};this.addCancel=function(){var c=this;$("#"+this.FieldID+" input:button").click(function(){c.Form.PreviousForm.NextForm=null;c.Form.PreviousForm.showFooter();c.Form.PreviousForm=null;var g=$("#"+c.Form.FormKey).parent();$("#"+c.Form.FormKey).remove();g.find("div.performs-form-div:last").show()})}};performs_FieldButton.prototype=new performs_Field;
var performs_FieldMultiSelectBox=function(f,h,a,b,e,d){this.base(f,h,a,b,"FieldMultiSelectBox","performs-field-fieldmultiselectbox","performs_fieldtemplate_multiselectbox",d);this.KeyValues=e;this.OnChange=function(){};this.validate=function(){var c=this.base_validate(this.getValues());this.showErrorMessages(c);return c.length==0};this.getValues=function(){var c=$("#"+this.FieldID+" select").multiselect("selectedValues");return c.length==0?[""]:c};this.setValues=function(c){var g=this;$(c).each(function(i,
j){$("#"+g.FieldID+" select").multiselect("select",$("#"+g.FieldID+" select").find("option[value='"+j+"']").text())})};this.updateItems=function(c){var g="";$(c).each(function(i,j){g+="<option value='"+j.Key+"'>"+j.Value+"</option>"});$("#"+this.FieldID+" select").multiselect("destroy");$("#"+this.FieldID+" select").html(g);this.applyMultiSelectBox()};this.renderField=function(){var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()};this.applyMultiSelectBox=function(){$("#"+
this.FieldID+" select").multiselect({animated:"fast",droppable:"none",sortable:"none",nodeComparator:null,searchDelay:0,dividerLocation:0.5,onChange:this.OnChange})};this.addGetAJAXActions=function(c,g){var i=this;this.OnChange=function(){performs_GetAJAXActions(i.Form,c,g)}}};performs_FieldMultiSelectBox.prototype=new performs_Field;
var performs_FieldGridView=function(f,h,a,b,e,d,c,g,i,j,k){this.base(f,h,a,b,"FieldGridView","performs-field-fieldgridview","performs_fieldtemplate_gridview",k);this.Columns=e;this.Rows=d;this.ActionKey=c;this.ClientSide=g;this.TableLabel=i;this.MultipleSelection=j;this.validate=function(){var l=this.base_validate(this.getValues());this.showErrorMessages(l);return l.length==0};this.getValues=function(){if(this.MultipleSelection){var l=$("#"+this.FieldID+"-gridview").getGridParam("selarrrow");if(l.length==
0)l=[""];return l}else return[$("#"+this.FieldID+"-gridview").getGridParam("selrow")]};this.setValues=function(){};this.renderField=function(){var l=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(l);return l.html()};this.applyGridView=function(){var l=this,m=[];$(this.Columns).each(function(n,o){m[m.length]=o.column});this.ClientSide?$("#"+this.FieldID+"-gridview").jqGrid({datatype:"local",data:this.Rows,colNames:m,colModel:this.Columns,rowNum:10,rowList:[10,20,30],caption:this.TableLabel,
pager:"#"+this.FieldID+"-pager",sortname:m[0],sortorder:"asc",height:"100%",autowidth:false,viewrecords:true,gridview:true,hidegrid:false,hoverrows:false,ignoreCase:true,multiselect:l.MultipleSelection,onSelectRow:function(){l.clearErrorMessages()}}):$("#"+this.FieldID+"-gridview").jqGrid({url:"PerForms/GetDataTable.aspx?actionKey="+this.ActionKey,datatype:"json",colNames:m,colModel:this.Columns,rowNum:10,rowList:[10,20,30],caption:this.TableLabel,pager:"#"+this.FieldID+"-pager",sortname:m[0],sortorder:"asc",
height:"100%",autowidth:false,viewrecords:true,gridview:true,hidegrid:false,hoverrows:false,multiselect:l.MultipleSelection,onSelectRow:function(){l.clearErrorMessages()}});$("#"+this.FieldID+"-gridview").jqGrid("navGrid","#"+this.FieldID+"-pager",{edit:false,add:false,del:false,refresh:false},{},{},{},{multipleSearch:true});this.ActionKey!=null&&this.ActionKey!=""&&$("#"+this.FieldID+"-gridview").jqGrid("navButtonAdd","#"+this.FieldID+"-pager",{buttonicon:"ui-icon-document",title:performs_Translate("[ExportToExcel]"),
caption:performs_Translate("[ExportToExcel]"),onClickButton:function(){window.open("PerForms/FileDownload.aspx?actionKey="+l.ActionKey)}});$("#"+this.FieldID+"-gridview").jqGrid("gridResize",{})}};performs_FieldGridView.prototype=new performs_Field;
var performs_FieldLabel=function(f,h,a,b,e){this.base(f,h,a,b,"FieldLabel","performs-field-fieldlabel","performs_fieldtemplate_label",e);this.validate=function(){return true};this.getValues=function(){return[$("#"+this.FieldID+" span")[0].innerHTML]};this.setValues=function(d){$("#"+this.FieldID+" span")[0].innerHTML=d[0]};this.renderField=function(){var d=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(d);return d.html()}};performs_FieldLabel.prototype=new performs_Field;
var performs_FieldDate=function(f,h,a,b,e){this.base(f,h,a,b,"FieldDate","performs-field-fielddate","performs_fieldtemplate_date",e);this.validate=function(){var d=this.base_validate(this.getValues());this.showErrorMessages(d);return d.length==0};this.getValues=function(){return[$("#"+this.FieldID+" input:text")[0].value]};this.setValues=function(d){$("#"+this.FieldID+" input:text")[0].value=d[0]};this.renderField=function(){$("#"+this.FieldID+" input:text").live("hover",function(){$(this).toggleClass("ui-state-hover")}).live("focus",
function(){$(this).addClass("ui-state-focus")}).live("blur",function(){$(this).removeClass("ui-state-focus")});var d=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(d);return d.html()};this.applyDatePicker=function(){var d=$("#"+this.FieldID+" input.performs-field-fielddate-input");$("<span style='position: absolute;' class='ui-state-default'><span style='margin-top: 5px; margin-left: 3px;' class='ui-icon ui-icon-calendar'></span></span>").insertAfter(d).width(25).height(d.height()+
10).hover(function(){$(this).toggleClass("ui-state-hover")}).click(function(){d.datepicker({showAnim:"",dayNamesMin:[performs_Translate("[Sunday_Short]"),performs_Translate("[Monday_Short]"),performs_Translate("[Tuesday_Short]"),performs_Translate("[Wednesday_Short]"),performs_Translate("[Thursday_Short]"),performs_Translate("[Friday_Short]"),performs_Translate("[Saturday_Short]")],monthNames:[performs_Translate("[January]"),performs_Translate("[February]"),performs_Translate("[March]"),performs_Translate("[April]"),
performs_Translate("[May]"),performs_Translate("[June]"),performs_Translate("[July]"),performs_Translate("[August]"),performs_Translate("[September]"),performs_Translate("[October]"),performs_Translate("[November]"),performs_Translate("[December]")],dateFormat:performs_Translate("[Date_Format_Long]")});d.datepicker("show")})}};performs_FieldDate.prototype=new performs_Field;
var performs_FieldUpload=function(f,h,a,b,e,d){this.base(f,h,a,b,"FieldUpload","performs-field-fieldupload","performs_fieldtemplate_upload",d);this.Root=e;this.Files=[];this.validate=function(){return true};this.getValues=function(){if(this.Files.length==0)return[""];else{var c=[];$(this.Files).each(function(g,i){c[c.length]=i.guid;c[c.length]=i.filename});return c}};this.setValues=function(){};this.renderField=function(){var c=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(c);return c.html()};
this.applyUpload=function(){var c=this,g=$("#"+c.FieldID+" div.performs-field-fieldupload-upload")[0];new qq.FileUploader({element:g,action:c.Root+"PerForms/FileUploader.ashx",onComplete:function(i,j,k){if(k.success)c.Files[c.Files.length]={guid:k.guid,filename:k.filename}},template:'<div class="qq-uploader"><table cellspacing="0" cellpadding="0" border="0"><tr><td><div class="qq-upload-button ui-state-default ui-corner-all" style="padding: 4px 11px 4px 11px;">'+performs_Translate("[ChooseFile]")+
'</div></td><td><div class="qq-upload-drop-area"><span>'+performs_Translate("[DropFileHere]")+'</span></div></td><td><ul class="qq-upload-list"></ul></td></tr></table></div>',fileTemplate:'<li><span class="qq-upload-file"></span><span class="qq-upload-spinner" style="display: none"></span><span class="qq-upload-size"></span><a class="qq-upload-cancel" href="#">'+performs_Translate("[Cancel]")+'</a><span class="qq-upload-failed-text">Failed</span></li>'});$("#"+c.FieldID+" div.qq-upload-button").mousedown(function(){$(this).addClass("ui-state-active")}).mouseup(function(){$(this).removeClass("ui-state-active")})}};
performs_FieldUpload.prototype=new performs_Field;var performs_FieldFree=function(f,h,a,b,e,d,c,g){this.base(f,h,a,b,"FieldFree","performs-field-fieldfree","performs_fieldtemplate_free",g);this.Source=e;this.GetValues=d;this.SetValues=c;this.validate=function(){return true};this.getValues=function(){this.GetValues()};this.setValues=function(i){this.SetValues(i)};this.renderField=function(){var i=$("<div />");$("#performs_fieldtemplate").tmpl(this).appendTo(i);return i.html()}};
performs_FieldFree.prototype=new performs_Field;